import React, { useEffect, useState } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";
// import { useAuth } from "hooks";
import axiosClient from "@/api/base/axios-client";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Adaptive Learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Trang chủ</div>
    </div>
  );
}

Home.permission = "public";
